blueprint:
  name: Restore Samba Backup sensor on startup
  description: Restore Samba Backup sensor on startup
  domain: automation
  input:
    app:
      name: Samba Backup App
      description: Select the Samba Backup app.
      selector:
        app:

mode: single

trigger:
  - event: start
    platform: homeassistant

action:
  - action: hassio.app_stdin
    data:
      app: !input app
      input: restore-sensor
